export enum CRMEventType {
    UserCreated = 'UserCreated',
    UserUpdated = 'UserUpdated',
    UserLevelChanged = 'UserLevelChanged',
    UserProfileUpdated = 'UserProfileUpdated',
    SubscriptionCreated = 'SubscriptionCreated',
    SubscriptionRenewed = 'SubscriptionRenewed',
    SubscriptionCancelling = 'SubscriptionCancelling',
    SubscriptionCancelled = 'SubscriptionCancelled',
    SubscriptionReactivated = 'SubscriptionReactivated',
    SubscriptionExpired = 'SubscriptionExpired',
    SubscriptionPastDue = 'SubscriptionPastDue',
    TournamentEntered = 'TournamentEntered',
    TournamentWin = 'TournamentWin',
    TournamentLoss = 'TournamentLoss',
    TournamentJackpotWin = 'TournamentJackpotWin',
    TournamentJackpotLoss = 'TournamentJackpotLoss',
    HasPurchased = 'HasPurchased',
    HasPurchasedDiamonds = 'HasPurchasedDiamonds'
}
