SERVICE: ${self:service.name}
DOMAIN: ${self:custom.common.domain}
BRAND: ${opt:brand}
STAGE: ${self:provider.stage}
AWS_ACC: ${self:custom.common.aws.accountId}
REGION: ${self:provider.region}
DB_GLOBAL_WR_ENDPOINT: ${ssm:/${self:provider.stage}/rds/global/${self:custom.common.defaultRegion}/endpoint-write}
DB_GLOBAL_RO_ENDPOINT: ${ssm:/${self:provider.stage}/rds/global/${self:provider.region}/endpoint-ro}
DB_GLOBAL_PORT: 3306
DB_GLOBAL_NAME: global
DB_GLOBAL_USERNAME: api_user
REDIS_CLUSTER_ENDPOINT: ${self:provider.region}.redis.cluster.${self:custom.common.domain}
SUBNETS: "${ssm:/${self:provider.stage}/vpc/${self:provider.region}/subnetId1~true},${ssm:/${self:provider.stage}/vpc/${self:provider.region}/subnetId2~true},${ssm:/${self:provider.stage}/vpc/${self:provider.region}/subnetId3~true}"
WEB_PURIFY_ENABLED: false
WEB_PURIFY_APIKEY: da513d894407a367343bf1960262ff59
CONTENT_BUCKET: origin.content.${self:custom.common.domain}
CONTENT_BASE_URL: https://content.${self:custom.common.domain}
ROLLBAR_ACCESS_TOKEN: ${ssm:/${self:provider.stage}/integration/rollbar/access-token~true}
VERIFICATION_BUCKET: io.tgaming.${self:provider.stage}.${opt:brand}.players
ADMIN_USER_POOL_ID: ${self:custom.common.admin.cognito.userPoolId}
NODE_OPTIONS: --tls-min-v1.0