service: 
  name: service-management-upgrade
  enabled: ${self:custom.brand.features.upgrades, "true"}

plugins:
  - serverless-plugin-enabled
  - serverless-api-compression
  - serverless-webpack
  - serverless-domain-manager
  - serverless-offline
  - serverless-plugin-scripts

provider:
  versionFunctions: false
  name: aws
  runtime: nodejs14.x
  memorySize: ${self:custom.common.provider.memorySize}
  region: ${opt:region, "${self:custom.common.defaultRegion}"}
  stage: ${opt:stage}
  logRetentionInDays: ${self:custom.common.logRetention}
  iamRoleStatements: ${file(../../serverless/iam-role.yml):statements}
  environment: ${file(../../../serverless/environment.yml)}
  profile: ${self:custom.common.aws.profile}
  usagePlan: ${self:custom.common.provider.usagePlan}
  vpc: ${self:custom.common.provider.vpc}

custom:
  brand: ${file(../../../brands.json):${opt:brand}}
  common: ${file(../../../serverless/common.yml)}
  customDomain:
    basePath: upgrade
    domainName: mgnt.${self:custom.common.domain}
  webpack:
      packager: 'yarn'
      includeModules: true
  serverless-offline:
    port: 3000
  contentCompression: 100
  scripts:
    hooks:
      'package:initialize': yarn build

functions:
  app: ${file(../../serverless/api.yml):appFunction}
